### ISSUE TITLE
emacs/vim support

### ISSUE THREAD

**Issue by kerrhau** [stayradiated/termcolors#10]
Support for exporting to editors such as emacs or vim would be nice, especially for the more obscure colour schemes such as trim-yer-beard.

**Comment by stayradiated** [comment]
While I agree it would be cool, I think it is outside the scope for this project.

`termcolors` is for managing terminal colour schemes, which have a simple system: 16 colours + background + foreground. It is simple to adapt a colour scheme to many terminals this way.

Editors (such as vim and emacs) can have many different colours, and are configured based on syntax highlighting and editor specific settings. If I were to add support for them, I would have to make a choice abuot which of the 16 terminal colours should be used for which parts of the editor. This may work great for a few schemes, but might look terrible for other schemes.

As an alternative, I would suggest finding a vim/emacs scheme that makes use of the 16 terminal colours (instead of fixed rgb values). For example: `shblah.vim` https://github.com/stayradiated/dotfiles/blob/master/apps/vim/colors/shblah.vim
