### ISSUE TITLE
feature: vim colors

### ISSUE THREAD

**Issue by sigmap** [stayradiated/termcolors#7]
Support for vim color themes, export/import

**Comment by Kaligule** [comment]
This is basically #10

**Comment by bignimbus** [comment]
Vim does have its own terminal.  https://vimhelp.org/terminal.txt.html `g:terminal_ansi_colors`. We could offer the option to export to a simple vimscript:

```vim
let g:terminal_ansi_colors = [
        \'#000000',
        \'#d70061',
        \'#3ad900',
        \'#ff9d00',
        \'#008ec2',
        \'#9f1ece',
        \'#40e0d0',
        \'#ffffff',
        \'#8787af',
        \'#ff005f',
        \'#5ff967',
        \'#ffff00',
        \'#00bbff',
        \'#c526ff',
        \'#95e3db',
        \'#ffffff'
        \]
```

This isn't what someone would call a "vim theme" or "vim colorscheme" but since vim does have a standalone terminal emulator, it seems like it would be a valid export target.

**Comment by 318h7** [comment]
I agree to what is said in #10 
I use the described approach myself for getting the terminal colors for both vim and emacs. It's easier to make the .Xresources the source for the editor color and it is outside the scope of the current package.
